name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --pull --file Dockerfile --tag lazyfrosch/duplicity:latest

    - name: Test with volume
      run: ./test.sh

    - name: Test with SSH
      env:
        SSH_SERVER: ${{ secrets.SSH_SERVER }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir .ssh
        echo "${SSH_KNOWN_HOSTS}" >.ssh/known_hosts
        echo "${SSH_PRIVATE_KEY}" >.ssh/id_rsa
        chmod -R go= .ssh

        ./test-ssh.sh
