name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --pull --file Dockerfile --tag lazyfrosch/duplicity:latest

    - name: Test with volume
      run: ./test.sh

    #- name: Test with SSH
    #  run: ./test-ssh.sh
